; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Jun 13 2021 17:50:32 GMT+0200 (Central European Summer Time)
M561 ; clear any bed transform

M671 S20
G30 P2 X345 Y330 Z-99999 ; probe near a leadscrew
G30 P3 X345 Y12 Z-99999 ; probe near a leadscrew
G30 P0 X9 Y12 Z-99999
G30 P1 X9 Y330 Z-99999 S4 ; probe near a leadscrew and calibrate 4 motors




